# Permalinks
permalink:        :title

# Setup
title:            lildude
tagline:          "GitHub's own lildude"
description:      "I'll come up with a whitty tagline one day"
url:              http://lildude.github.io
baseurl:

author:           'Colin Seymour'
github_username:  lildude
twitter_username: lildude

paginate:         5

theme: minima

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/lildude/lildude.github.io
