# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        :title

# Setup
title:            lildude
tagline:          "GitHub's own lildude"
description:      "I'll come up with a whitty tagline one day"
url:              http://lildude.github.io
baseurl:          /

author:
  name:           'Colin Seymour'
  url:            https://twitter.com/lildude

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/lildude/lildude.github.io
