# Permalinks
permalink:        :title

# Setup
title:            lildude
tagline:          "GitHub's own lildude"
description:      "I'll come up with a whitty tagline one day"
url:              http://lildude.github.io
baseurl:

author:           'Colin Seymour'
github_username:  lildude
twitter_username: lildude

micropub_endpoint:  https://micropubbing.herokuapp.com/micropub/main

paginate:         15

theme: minima

kramdown:
  input:            GFM
  smart_quotes:     ["apos", "apos", "quot", "quot"]  # Don't do smart quoting by replacing like for like.

plugins:
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/lildude/lildude.github.io
